---
- name: Apagar a pasta antiga do repositório
  become: yes
  shell: rm -r swap 
  ignore_errors: yes

- name: Git clone do repositório do swap
  git:
    repo: https://github.com/Hackathonners/swap.git
    dest: /home/vagrant/swap

- name: sudo add-apt-repository ppa:ondrej/php
  become: yes
  apt_repository:
    repo: ppa:ondrej/php

- name: sudo apt update
  become: yes
  apt:
    update_cache: yes

- name: sudo apt install php7.4 php7.4-{fpm,zIP,mbstring,tokenizer,mysql,gd,xml,bcmath,intl,curl}
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ php_packages }}"

- name: sudo apt install nodejs e sudo apt install composer e sudo apt install npm
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ outros_packages }}"

- name: composer install
  command: composer install
  args:
    chdir: ./swap

- name: npm install
  npm:
    path: ./swap

- name: Mudar as linhas do .env
  template: 
    src: /home/vagrant/roles/app/templates/env_example
    dest: /home/vagrant/swap/.env.example

- name: Renomear .env.example para .env
  command: mv .env.example .env
  args:
    chdir: ./swap

# matar todos os processos php que estejam a correr
- name: Clean previous app servers
  shell: killall -9 php7.4 && killall -9 php
  ignore_errors: yes

- name: php artisan key:generate
  become: yes
  command: php artisan key:generate
  args:
    chdir: ./swap

- name: php artisan migrate
  become: yes
  command: php artisan migrate
  args:
    chdir: ./swap

- name: php artisan serve --host=0.0.0.0
  become: yes
  shell: nohup php artisan serve --host=0.0.0.0 > app_out.log 2>&1 &
  args:
    chdir: ./swap