---
# Service for exposing MySQL
apiVersion: v1
kind: Service
metadata:
  name: swap-service # logical name of the service, which will also become the DNS name of the service when it is created.
  labels:
    app: swap
    tier: application
spec:
  type: NodePort # para ser acessível pelo browser
  selector:
    app: swap
  ports:
    - targetPort: 8000 # port that containers are listening on
      port: 8000 # port number exposed internally in the cluster
      nodePort: 30007